kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: my-cluster
networking:
  apiServerPort: 6443
nodes:
- role: control-plane
  image: kindest/node:v1.34.0
- role: worker
  image: kindest/node:v1.34.0
  extraMounts:
    - hostPath: ${PROJECT_PATH}/common/k8s/scylladb
      containerPath: /scylladb