services:
  scylla-node1:
    image: scylladb/scylla:4.6.3
    container_name: scylla-node1
    hostname: scylla-node1
    command: --smp 2 --memory 2G --cpuset 1,2
    volumes:
      - $COMMON_PATH/scylladb/data1:/var/lib/scylla
      - $PROJECT_PATH/lakehouse-platform/scylladb/config:/etc/scylla
    ports:
      - 9042:9042
    networks:
      - lakehouse_platform
  
  scylla-node2:
    image: scylladb/scylla:4.6.3
    container_name: scylla-node2
    hostname: scylla-node2
    command: --seeds scylla-node1 --smp 2 --memory 2G --cpuset 3,4
    volumes:
      - $COMMON_PATH/scylladb/data2:/var/lib/scylla
      - $PROJECT_PATH/lakehouse-platform/scylladb/config:/etc/scylla
    ports:
      - 9043:9042
    networks:
      - lakehouse_platform

networks:
  lakehouse_platform:
    external: true