services:
  scylla-node1:
    image: nitsvutt/scylla_with_agent:5.4.2
    container_name: scylla-node1
    command: --smp 2 --memory 2G --cpuset 1,2
    volumes:
      - $COMMON_PATH/scylladb/data1:/var/lib/scylla
      - $PROJECT_PATH/migration-project/scylladb/config/scylla.yaml:/etc/scylla/scylla.yaml
    ports:
      - 9042:9042
      - 10000:10000
      - 10001:10001
    networks:
      - lakehouse_platform
  
  scylla-node2:
    image: nitsvutt/scylla_with_agent:5.4.2
    container_name: scylla-node2
    command: --seeds scylla-node1 --smp 2 --memory 2G --cpuset 3,4
    volumes:
      - $COMMON_PATH/scylladb/data2:/var/lib/scylla
      - $PROJECT_PATH/migration-project/scylladb/config/scylla.yaml:/etc/scylla/scylla.yaml
    ports:
      - 9043:9042
    depends_on:
      - scylla-node1
    networks:
      - lakehouse_platform
  
  # scylla-node3:
  #   image: nitsvutt/scylla_with_agent:5.4.2
  #   container_name: scylla-node3
  #   command: --seeds scylla-node1 --smp 2 --memory 2G --cpuset 5,6
  #   volumes:
  #     - $COMMON_PATH/scylladb/data3:/var/lib/scylla
  #     - $PROJECT_PATH/migration-project/scylladb/config/scylla.yaml:/etc/scylla/scylla.yaml
  #   ports:
  #     - 9044:9042
  #   depends_on:
  #     - scylla-node1
  #   networks:
  #     - lakehouse_platform
  
  scylla-manager-db:
    image: scylladb/scylla:5.4.2
    container_name: scylla-manager-db
    volumes:
      - $COMMON_PATH/scylladb/manager_db:/var/lib/scylla
      - $PROJECT_PATH/migration-project/scylladb/config/scylla-manager-db.yaml:/etc/scylla/scylla.yaml
    command: --smp 1 --memory 1G --cpuset 7
    networks:
      - lakehouse_platform

  scylla-manager:
    image: scylladb/scylla-manager:3.4.2
    container_name: scylla-manager
    volumes:
      - $PROJECT_PATH/migration-project/scylladb/config/scylla-manager.yaml:/etc/scylla-manager/scylla-manager.yaml
    environment:
      - SCYLLADB_AUTH_TOKEN=$SCYLLADB_AUTH_TOKEN
    depends_on:
      - scylla-manager-db
    networks:
      - lakehouse_platform

networks:
  lakehouse_platform:
    external: true