apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla-config
  namespace: scylla
data:
  scylla.yaml: |
    cluster_name: 'my-cluster'
    num_tokens: 256
    commitlog_sync: periodic
    commitlog_sync_period_in_ms: 10000
    commitlog_segment_size_in_mb: 32
    schema_commitlog_segment_size_in_mb: 128
    seed_provider:
      - class_name: org.apache.cassandra.locator.SimpleSeedProvider
        parameters:
          - seeds: "scylla-0.scylla-clusterip.scylla.svc.cluster.local"
    listen_address: 0.0.0.0
    native_transport_port: 9042
    native_shard_aware_transport_port: 19042
    read_request_timeout_in_ms: 5000
    write_request_timeout_in_ms: 2000
    cas_contention_timeout_in_ms: 1000
    endpoint_snitch: SimpleSnitch
    rpc_address: 0.0.0.0
    api_port: 10000
    api_address: 0.0.0.0
    batch_size_warn_threshold_in_kb: 128
    batch_size_fail_threshold_in_kb: 1024
    partitioner: org.apache.cassandra.dht.Murmur3Partitioner
    commitlog_total_space_in_mb: -1
    murmur3_partitioner_ignore_msb_bits: 12
    strict_is_not_null_in_views: true
    maintenance_socket: ignore
    tablets_mode_for_new_keyspaces: enabled
    rf_rack_valid_keyspaces: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla-manager-config
  namespace: scylla
data:
  scylla.yaml: |
    cluster_name: 'manager-db-cluster'
    num_tokens: 256
    commitlog_sync: periodic
    commitlog_sync_period_in_ms: 10000
    commitlog_segment_size_in_mb: 32
    schema_commitlog_segment_size_in_mb: 128
    seed_provider:
      - class_name: org.apache.cassandra.locator.SimpleSeedProvider
        parameters:
          - seeds: "scylla-manager-0.scylla-manager-clusterip.scylla.svc.cluster.local"
    listen_address: 0.0.0.0
    native_transport_port: 9042
    native_shard_aware_transport_port: 19042
    read_request_timeout_in_ms: 5000
    write_request_timeout_in_ms: 2000
    cas_contention_timeout_in_ms: 1000
    endpoint_snitch: SimpleSnitch
    rpc_address: 0.0.0.0
    api_port: 10000
    api_address: 0.0.0.0
    batch_size_warn_threshold_in_kb: 128
    batch_size_fail_threshold_in_kb: 1024
    partitioner: org.apache.cassandra.dht.Murmur3Partitioner
    commitlog_total_space_in_mb: -1
    murmur3_partitioner_ignore_msb_bits: 12
    strict_is_not_null_in_views: true
    maintenance_socket: ignore
    tablets_mode_for_new_keyspaces: enabled
    rf_rack_valid_keyspaces: false
  scylla-manager.yaml: |
    http: :5080
    database:
      hosts:
        - scylla-manager-0.scylla-manager-clusterip.scylla.svc.cluster.local