apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scylladb
  namespace: scylladb
spec:
  serviceName: scylladb-clusterip
  selector:
    matchLabels:
      app: scylladb
  replicas: 2
  template:
    metadata:
      namespace: scylladb
      labels:
        app: scylladb
    spec:
      containers:
      - name: scylladb
        image: scylladb/scylla:4.6.3
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 2
            memory: 2Gi
        ports:
          - containerPort: 7000
            name: gossip
            protocol: TCP
          - containerPort: 7001
            name: sslinternode
            protocol: TCP
          - containerPort: 9042
            name: cql
            protocol: TCP
          - containerPort: 7199
            name: jmx
            protocol: TCP
        env:
          - name: SEEDS
            value: scylladb-0.scylladb-clusterip.scylladb.svc.cluster.local
        command:
          - bash
          - '-c'
          - >
            ./docker-entrypoint.py \
              --seeds ${SEEDS} \
              --smp 2 --memory 2G
        volumeMounts:
          - name: scylladb-pv
            mountPath: /var/lib/scylla
          - name: scylladb-config
            mountPath: /etc/scylla/scylla.yaml
            subPath: scylla.yaml
      volumes:
        - name: scylladb-config
          configMap:
            name: scylladb-config
  volumeClaimTemplates:
  - metadata:
      name: scylladb-pv
    spec:
      storageClassName: manual
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 10Gi