apiVersion: v1
kind: Service
metadata:
  name: scylladb-clusterip
  namespace: scylladb
spec:
  clusterIP: None
  selector:
    app: scylladb
  ports:
    - name: gossip
      port: 7000
      protocol: TCP
    - name: sslinternode
      port: 7001
      protocol: TCP
    - name: cql
      port: 9042
      protocol: TCP
    - name: jmx
      port: 7199
      protocol: TCP