services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - $COMMON_PATH/minio/data:/data
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3
    command: server /data --console-address ":9001"
    networks:
      - lakehouse_platform

  minio-client:
    image: minio/mc:latest
    container_name: minio-client
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - $COMMON_PATH/k8s/scylladb:/tmp/scylladb
      - $COMMON_PATH/scylladb/data1:/target/data1
      - $COMMON_PATH/scylladb/data2:/target/data2
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      tail -f /dev/null
      "
    networks:
      - lakehouse_platform

networks:
  lakehouse_platform:
    external: true